### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by kamilaprz** [stolsvik/mats#55]
There should definitely be `return` on line #511

https://github.com/stolsvik/mats/blob/63433e4c4435997ed69d3991e2a9a683f8a59ca9/mats-serial/src/main/java/com/stolsvik/mats/serial/impl/MatsTraceStringImpl.java#L511

**Comment by stolsvik** [comment]
Oh, this was fixed in the recent big commit.
https://github.com/stolsvik/mats/blob/8dfeef596ce9ccfe1740cd98c5b4ddd322ce057b/mats-serial/src/main/java/com/stolsvik/mats/serial/impl/MatsTraceStringImpl.java#L512-L515
